GET https://bd.kinokong.org/22926-gomorra-1-4-sezon-2019.html

###

GET http://4565.videocdn.pw/Z9w3z4ZBIQxF/tv-series/5409


###

GET https://vid1576263065.vb17106cecilgregory.pw/movie/48a78d276070aa5fbe6ab620c5dfe8a8/iframe
#
#accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
#referer: https://bd.kinokong.org/36897-zhivotnye-2019.html
#sec-fetch-mode: nested-navigate
#sec-fetch-site: cross-site
#upgrade-insecure-requests: 1
#user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
####

GET http://4565.videocdn.pw/Z9w3z4ZBIQxF/tv-series/5735

###

GET http://4565.videocdn.pw/iframe.js?id=21bb628b5f35ddb77eca

###